### ISSUE TITLE
Crash from turbine

### ISSUE THREAD

**Issue by bluelightning32** [mekanica/mekanica#15]
#### Issue description:
Often but not always when a chunk is loaded with a turbine in it, the server crashes. Usually the backtrace shows the turbine getting loaded when some other mod is trying to feed it.

This has happened with several of the turbines different players have built on the server. It didn't happen when I was running Enigmatica Expert2 1.55.

#### Steps to reproduce:
Build a turbine, then force it to get unloaded by loading other chunks, then fly by it to load it again.

#### Version (make sure you are on the latest version before reporting):
**Forge:** forge-1.12.2-14.23.5.2781-universal.jar
**Mekanism:** MekanismDz-1.12.2-9.4.17.jar
**Sponge:** spongeforge-1.12.2-2768-7.1.6-RC3563.jar
**Other relevant version:** Enigmatica Expert2 version 1.57

#### If a (crash)log is relevant for this issue, link it here: (_It's almost always relevant_)

[Crash report](https://gist.github.com/bluelightning32/0a667795452d0e5f1ec45b8198959d14)

Note, that crash is with [temporary logging](https://gist.github.com/bluelightning32/505f88b8c469c7f9ee29b1eaca35b9eb) I added to get more information on the crash. Here are the relevant parts of the debug log:
```
[23:34:11] [Server thread/INFO] [Sponge]: Unload Chunk At [0] (-86, -191)
[23:34:11] [Server thread/INFO] [Sponge]: Unload Chunk At [0] (-176, 32)
[23:34:11] [Server thread/INFO] [Sponge]: Load Chunk At [0] (-84, -193)
[23:34:11] [Server thread/INFO] [Sponge]: Load Chunk At [0] (-84, -189)
[23:34:11] [Server thread/INFO] [Sponge]: Load Chunk At [0] (-85, -189)
[23:34:11] [Server thread/INFO] [Sponge]: Load Chunk At [0] (-87, -193)
[23:34:11] [Server thread/INFO] [Sponge]: Load Chunk At [0] (-86, -192)
[23:34:11] [Server thread/INFO] [Sponge]: Load Chunk At [0] (-88, -192)
[23:34:12] [Server thread/INFO] [Mekanism]: Caught NPE for turbine rotor at x=-1373, y=7, z=-3053
[23:34:12] [Server thread/INFO] [Mekanism]: pointerAdvanced=0 rotorsAdded=0 was_rotor=false now_rotor=false
[23:34:12] [Server thread/ERROR] [FML]: Exception caught during firing event net.minecraftforge.event.world.ChunkEvent$Load@78f0d664:
java.lang.NullPointerException: null
        at mekanism.generators.common.tile.turbine.TileEntityTurbineRotor.buildRotors(TileEntityTurbineRotor.java:91) ~[TileEntityTurbineRotor.class:?]
        at mekanism.generators.common.tile.turbine.TileEntityTurbineRotor.updateRotors(TileEntityTurbineRotor.java:56) ~[TileEntityTurbineRotor.class:?]
        at mekanism.generators.common.tile.turbine.TileEntityTurbineRotor.onChunkLoad(TileEntityTurbineRotor.java:206) ~[TileEntityTurbineRotor.class:?]
        at mekanism.common.Mekanism.onChunkLoad(Mekanism.java:952) ~[Mekanism.class:?]
        at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_2147_Mekanism_onChunkLoad_Load.invoke(.dynamic) ~[?:?]
        at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) ~[ASMEventHandler.class:?]
        at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:746) [EventBus.class:?]
        at org.spongepowered.mod.event.SpongeToForgeEventFactory.createAndPostChunkLoadEvent(SpongeToForgeEventFactory.java:963) [SpongeToForgeEventFactory.class:1.12.2-2768-7.1.6-RC3563]
```

**Comment by bluelightning32** [comment]
![turbine](https://user-images.githubusercontent.com/21202621/54259792-2695c700-4524-11e9-8042-4396fdfdfb35.png)

**Comment by dizzyd** [comment]
Hi @bluelightning32 - thanks for the report. I was wondering if you could provide a little more context:
1. Is the turbine contained entirely within a chunk or does it span 2, 3 or more chunks?
2. What is feeding it steam? AE2? Does the steam source span chunks?

Thanks!

**Comment by bluelightning32** [comment]
In the one I attached the screenshot for, it was entirely in one chunk.
You  can sort of see the chunk boundaries in the screenshot. You  can also
tell from the coords of the center rotor.

In most of these crashes, the steam came from a fluix plug. I'm sure the
network spanned chunks, and in the stack traces it often looks like the
network is sending its last item because its chunk is going to be unloaded,
which loads the turbine chunk.

**Comment by dizzyd** [comment]
I've completely overhauled how rotors work and these issues should be fully resolved in next release. 

Famous last words... :)
